# Задачи с сайта sql-ex.ru


In [1]:
# !wget https://sql-ex.ru/download/sql-ex-pg.sql

# utf-8-sig - разновидность UTF-8, автоматически удаляющая BOM (Byte Order Mark) из начала файла.
with open("sql-ex-pg.sql", "r", encoding="utf-8-sig") as file:
    sql = file.read()

In [2]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://postgres:root@localhost:5432/psql_db")

# SQLAlchemy в режиме engine.connect() работает внутри транзакции, которая не коммитится автоматически, если не использовать begin().
with engine.begin() as con:  # Решение: engine.begin() - транзакция автокоммитятся
    for statement in sql.split(";"):
        stmt = statement.strip()
        if stmt:
            con.execute(text(stmt))

In [3]:
def select(sql):
    with engine.connect() as con:
        return pd.read_sql(sql, con)

## Краткая информация о базе данных "Компьютерная фирма"

Схема БД состоит из четырех таблиц:
Product(maker, model, type)
PC(code, model, speed, ram, hd, cd, price)
Laptop(code, model, speed, ram, hd, price, screen)
Printer(code, model, color, type, price)
Таблица Product представляет производителя (maker), номер модели (model) и тип ('PC' - ПК, 'Laptop' - ПК-блокнот или 'Printer' - принтер). Предполагается, что номера моделей в таблице Product уникальны для всех производителей и типов продуктов. В таблице PC для каждого ПК, однозначно определяемого уникальным кодом – code, указаны модель – model (внешний ключ к таблице Product), скорость - speed (процессора в мегагерцах), объем памяти - ram (в мегабайтах), размер диска - hd (в гигабайтах), скорость считывающего устройства - cd (например, '4x') и цена - price (в долларах). Таблица Laptop аналогична таблице РС за исключением того, что вместо скорости CD содержит размер экрана -screen (в дюймах). В таблице Printer для каждой модели принтера указывается, является ли он цветным - color ('y', если цветной), тип принтера - type (лазерный – 'Laser', струйный – 'Jet' или матричный – 'Matrix') и цена - price.


### Задание 1

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd


In [4]:
sql = """--sql
SELECT
    pc.model,
    pc.speed,
    pc.hd
FROM
    pc
WHERE
    price < 500
ORDER BY
    pc.model,
    pc.speed,
    pc.hd
"""
select(sql)

,model,speed,hd
0,1232,450,8.0
1,1232,450,10.0
2,1232,500,10.0
3,1260,500,10.0


### Задание 2

Найдите производителей принтеров. Вывести: maker


In [5]:
sql = """--sql
SELECT DISTINCT
    p.maker
FROM
    product p
WHERE
    type LIKE 'Printer'
ORDER BY
    p.maker
"""
select(sql)

,maker
0,A
1,D
2,E


### Задание 3

Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.


In [6]:
sql = """--sql
SELECT
    l.model,
    l.ram,
    l.screen
FROM
    laptop l
WHERE
    l.price > 1000
ORDER BY
    l.model,
    l.ram,
    l.screen
"""
select(sql)

,model,ram,screen
0,1298,64,15
1,1750,128,14
2,1752,128,14


### Задание 4

Найдите все записи таблицы Printer для цветных принтеров.


In [7]:
sql = """--sql
SELECT
    p.*
FROM
    printer p
WHERE
    color = 'y'
"""
select(sql)

,code,model,color,type,price
0,2,1433,y,Jet,270.0
1,3,1434,y,Jet,290.0


### Задание 5

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.


In [8]:
sql = """--sql
SELECT
    pc.model,
    pc.speed,
    pc.hd
FROM
    pc
WHERE
    pc.cd IN ('12x', '24x')
    AND pc.price < 600
ORDER BY
    pc.model,
    pc.speed,
    pc.hd
"""
select(sql)

,model,speed,hd
0,1232,450,8.0
1,1232,450,10.0
2,1232,500,10.0
3,1260,500,10.0


### Задание 6

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.


In [9]:
sql = """--sql
SELECT DISTINCT
    p.maker,
    l.speed
FROM
    product p
    INNER JOIN laptop l ON p.model = l.model
WHERE
    l.hd >= 10
ORDER BY
    p.maker,
    l.speed
"""
select(sql)

,maker,speed
0,A,450
1,A,600
2,A,750
3,B,750


### Задание 7

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).


In [10]:
sql = """--sql
SELECT
    ap.*
FROM
    (
        SELECT
            pc.model,
            pc.price
        FROM
            pc
        UNION
        SELECT
            l.model,
            l.price
        FROM
            laptop l
        UNION
        SELECT
            pr.model,
            pr.price
        FROM
            printer pr
    ) ap
WHERE
    ap.model IN (
        SELECT
            p.model
        FROM
            product p
        WHERE
            p.maker = 'B'
    )
ORDER BY
    ap.model,
    ap.price desc
"""
select(sql)

,model,price
0,1121,850.0
1,1750,1200.0


### Задание 8

Найдите производителя, выпускающего ПК, но не ПК-блокноты.


In [11]:
sql = """--sql
SELECT DISTINCT
    p.maker
FROM
    product p
WHERE
    p.maker NOT IN (
        SELECT DISTINCT
            p.maker
        FROM
            product p
        WHERE
            p.type = 'Laptop'
    )
    AND p.maker IN (
        SELECT DISTINCT
            p.maker
        FROM
            product p
        WHERE
            p.type = 'PC'
    )
"""
select(sql)

,maker
0,E


### Задание 9

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker


In [12]:
sql = """--sql
SELECT DISTINCT
    p.maker
FROM
    product p
    RIGHT JOIN pc ON p.model = pc.model
WHERE
    pc.speed >= 450
ORDER BY
    p.maker
"""
select(sql)

,maker
0,A
1,B
2,E


### Задание 10

Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price


In [13]:
sql = """--sql
SELECT
    p.model,
    p.price
FROM
    printer p
WHERE
    p.price = (
        SELECT
            MAX(p.price)
        FROM
            printer p
    )
ORDER BY
    p.model
"""
select(sql)

,model,price
0,1276,400.0
1,1288,400.0


### Задание 11

Найдите среднюю скорость ПК.


In [14]:
sql = """--sql
SELECT
    ROUND(AVG(pc.speed), 2) AS avg_speed
FROM
    pc
"""
select(sql)

,avg_speed
0,608.33


### Задание 12

Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.


In [15]:
sql = """--sql
SELECT
    AVG(l.speed) AS avg_speed
FROM
    laptop l
WHERE
    l.price > 1000
"""
select(sql)

,avg_speed
0,700.0


### Задание 13

Найдите среднюю скорость ПК, выпущенных производителем A.


In [16]:
sql = """--sql
SELECT
    AVG(pc.speed) AS avg_speed
FROM
    pc
    LEFT JOIN product p ON pc.model = p.model
WHERE
    p.maker = 'A'
"""
select(sql)

,avg_speed
0,606.25


### Задание 15

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD


In [17]:
sql = """--sql
SELECT
    cnt.hd
FROM
    (
        SELECT
            pc.hd,
            COUNT(*)
        FROM
            pc
        GROUP BY
            pc.hd
    ) cnt
WHERE
    cnt.count > 1
ORDER BY
    cnt.hd
"""
select(sql)

,hd
0,5.0
1,8.0
2,10.0
3,14.0
4,20.0


### Задание 16

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.


In [18]:
sql = """--sql
SELECT DISTINCT
    f.model AS top_mode,
    s.model AS low_model,
    f.speed,
    f.ram
FROM
    pc f
    INNER JOIN (
        SELECT
            pc.model,
            pc.speed,
            pc.ram
        FROM
            pc
    ) AS s ON f.speed = s.speed
    AND f.ram = s.ram
    AND f.model > s.model
ORDER BY
    f.model,
    s.model
"""
select(sql)

,top_mode,low_model,speed,ram
0,1233,1121,750,128
1,1233,1232,500,64
2,1260,1232,500,32


### Задание 17

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed


In [19]:
sql = """--sql
SELECT DISTINCT
    p.type,
    l.model,
    l.speed
FROM
    laptop l
    LEFT JOIN product p ON l.model = p.model
WHERE
    l.speed < (
        SELECT
            MIN(pc.speed) AS min_speed_pc
        FROM
            pc
    )
ORDER BY
    l.model,
    l.speed
"""
select(sql)

,type,model,speed
0,Laptop,1298,350


### Задание 18

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price


In [20]:
sql = """--sql
SELECT DISTINCT
    pd.maker,
    pr.price
FROM
    printer pr
    LEFT JOIN product pd ON pr.model = pd.model
WHERE
    pr.price = (
        SELECT
            MIN(pr.price) AS min_price
        FROM
            printer pr
        WHERE
            pr.color = 'y'
    )
    AND pr.color = 'y'
ORDER BY
    pd.maker,
    pr.price desc
"""
select(sql)

,maker,price
0,D,270.0


### Задание 19

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.


In [21]:
sql = """--sql
SELECT
    p.maker,
    AVG(l.screen) AS avg_screen
FROM
    laptop l
    LEFT JOIN product p ON l.model = p.model
GROUP BY
    p.maker
ORDER BY
    avg_screen desc
"""
select(sql)

,maker,avg_screen
0,B,14.0
1,A,13.0
2,C,12.0


### Задание 20

Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.


In [22]:
sql = """--sql
SELECT
    p.maker,
    COUNT(*) AS num_models
FROM
    product p
WHERE
    p.type = 'PC'
GROUP BY
    p.maker
HAVING
    COUNT(*) >= 3
ORDER BY
    num_models desc
"""
select(sql)

,maker,num_models
0,E,3


### Задание 21

Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.


In [23]:
sql = """--sql
SELECT
    p.maker,
    MAX(pc.price) AS max_price
FROM
    pc
    LEFT JOIN product p ON pc.model = p.model
GROUP BY
    p.maker
ORDER BY
    max_price desc
"""
select(sql)

,maker,max_price
0,A,980.0
1,B,850.0
2,E,350.0


### Задание 22

Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.


In [24]:
sql = """--sql
SELECT
    pc.speed,
    AVG(pc.price) AS avg_price
FROM
    pc
WHERE
    pc.speed > 600
GROUP BY
    pc.speed
ORDER BY
    avg_price desc
"""
select(sql)

,speed,avg_price
0,900,980.0
1,800,970.0
2,750,900.0


### Задание 23

Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker


In [25]:
sql = """--sql
SELECT
    pc.maker
FROM
    (
        SELECT DISTINCT
            p.maker
        FROM
            product p
        WHERE
            p.model IN (
                SELECT
                    pc.model
                FROM
                    pc
                WHERE
                    pc.speed >= 750
            )
    ) pc
    INNER JOIN (
        SELECT DISTINCT
            p.maker
        FROM
            product p
        WHERE
            p.model IN (
                SELECT
                    l.model
                FROM
                    laptop l
                WHERE
                    l.speed >= 750
            )
    ) l ON pc.maker = l.maker
ORDER BY
    pc.maker
"""
select(sql)

,maker
0,A
1,B


### Задание 24

Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.


In [26]:
sql = """--sql
WITH
    all_model AS (
        SELECT
            pc.model,
            pc.price
        FROM
            pc
        UNION
        SELECT
            p.model,
            p.price
        FROM
            printer p
        UNION
        SELECT
            l.model,
            l.price
        FROM
            laptop l
    )
SELECT
    am.model
FROM
    all_model am
WHERE
    am.price IN (
        SELECT
            MAX(price)
        FROM
            all_model
    )
ORDER BY
    am.model
"""
select(sql)

,model
0,1750


### Задание 25

Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker


In [27]:
sql = """--sql
WITH
    pc_makers AS (
        SELECT DISTINCT
            p.maker
        FROM
            product p
            RIGHT JOIN (
                SELECT DISTINCT
                    pc.model,
                    pc.ram,
                    pc.speed,
                    RANK() OVER (
                        ORDER BY
                            pc.ram,
                            pc.speed desc
                    ) AS RANK
                FROM
                    pc
            ) m ON p.model = m.model
        WHERE
            m.rank = 1
    )
SELECT DISTINCT
    p.maker
FROM
    product p
WHERE
    p.type = 'Printer'
    AND p.maker IN (
        SELECT
            maker
        FROM
            pc_makers
    )
ORDER BY
    p.maker
"""
select(sql)

,maker
0,A
1,E


### Зфдание 26

Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.


In [28]:
sql = """--sql
SELECT
    AVG(m.price)
FROM
    product p
    RIGHT JOIN (
        SELECT
            pc.model,
            pc.price
        FROM
            pc
        UNION ALL
        SELECT
            l.model,
            l.price
        FROM
            laptop l
    ) m ON p.model = m.model
WHERE
    p.maker = 'A'
GROUP BY
    p.maker
"""
select(sql)

,avg
0,754.166667


### Задание 27

Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.


In [29]:
sql = """--sql
SELECT
    p.maker,
    AVG(pc.hd) AS avg_hd
FROM
    pc
    LEFT JOIN product p ON pc.model = p.model
WHERE
    p.maker IN (
        SELECT DISTINCT
            p.maker
        FROM
            product p
        WHERE
            p.type = 'Printer'
    )
GROUP BY
    p.maker
ORDER BY
    avg_hd desc
"""
select(sql)

,maker,avg_hd
0,A,14.75
1,E,10.00


### Задание 28

Используя таблицу Product, определить количество производителей, выпускающих по одной модели.


## Краткая информация о базе данных "Корабли"

Рассматривается БД кораблей, участвовавших во второй мировой войне. Имеются следующие отношения:
Classes (class, type, country, numGuns, bore, displacement)
Ships (name, class, launched)
Battles (name, date)
Outcomes (ship, battle, result)
Корабли в «классах» построены по одному и тому же проекту, и классу присваивается либо имя первого корабля, построенного по данному проекту, либо названию класса дается имя проекта, которое не совпадает ни с одним из кораблей в БД. Корабль, давший название классу, называется головным.
Отношение Classes содержит имя класса, тип (bb для боевого (линейного) корабля или bc для боевого крейсера), страну, в которой построен корабль, число главных орудий, калибр орудий (диаметр ствола орудия в дюймах) и водоизмещение ( вес в тоннах). В отношении Ships записаны название корабля, имя его класса и год спуска на воду. В отношение Battles включены название и дата битвы, в которой участвовали корабли, а в отношении Outcomes – результат участия данного корабля в битве (потоплен-sunk, поврежден - damaged или невредим - OK).
Замечания. 1) В отношение Outcomes могут входить корабли, отсутствующие в отношении Ships. 2) Потопленный корабль в последующих битвах участия не принимает.


### Задание 14

Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.


In [30]:
sql = """--sql
SELECT
    s.class,
    s.name,
    c.country
FROM
    ships s
    LEFT JOIN classes c ON s.class = c.class
WHERE
    c.numguns >= 10
"""
select(sql)

,class,name,country
0,Tennessee,California,USA
1,North Carolina,North Carolina,USA
2,Tennessee,Tennessee,USA
3,North Carolina,Washington,USA
4,North Carolina,South Dakota,USA
